---
# tasks file for patroni
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add postgres repository to source list
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
    state: present

- name: install postgresql, etcd, 
  apt:
    name:
      - postgresql-client-11
      - postgresql-11
      - libpq-dev
      - postgresql-server-dev-11
      - etcd
      - python-etcd
      - patroni

- name: ansible create config directory patroni
  file:
    path: /etc/patroni
    state: directory

- name: create config and templates file
  template:
    src: "{{item}}"
    des: "/{{item}}"
    state: present
  with_items:
    - etc/patroni/config.yml

- name: enable and start patroni service
  service:
    name: patroni
    enabled: yes
    state: started
