---
# tasks file for patroni
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add postgres repository to source list
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
    state: present

- name: install postgresql, etcd, 
  apt:
    name:
      - postgresql-client-11
      - postgresql-11
      - libpq-dev
      - postgresql-server-dev-11
      - etcd
      - python-etcd
      - patroni

- name: disable postgresql service
  service:
    name: postgresql@11-main
    enabled: no
    state: stopped

- name: state main directory
  stat: path=/var/lib/postgresql/11/main
  register: pg_main_data_dir_stat

- name: rename old data directory
  command: mv /var/lib/postgresql/11/main /var/lib/postgresql/11/main_old
  when: pg_main_data_dir_stat.stat.exists


- name: ansible create config directory patroni
  file:
    path: /etc/patroni
    state: directory


- name: ansible create config directory patroni
  file:
    path: /etc/etcd
    state: directory

- name:
  file: path=/var/etcd owner=etcd state=directory

- name: create config and templates file
  template:
    src: "{{item}}"
    dest: "/{{item}}"
  with_items:
    - etc/patroni/config.yml
    - etc/patroni/handler.py
    - lib/systemd/system/etcd.service
    - lib/systemd/system/patroni.service
    - etc/etcd/etcd.conf.yml
    - etc/hosts

- name:
  file: path=etc/patroni/handler.py mode="u+rw,g-wx,o-rwx" state=file

- name:
  command: systemctl daemon-reload

- name: enable and restart patroni service
  service:
    name: patroni
    enabled: yes
    state: restarted

- name: enable and start patroni service
  service:
    name: patroni
    enabled: yes
    state: started

- name: enable and restart etcd service
  service:
    name: etcd
    enabled: yes
    state: restarted

- name: enable and start etcd service
  service:
    name: etcd
    enabled: yes
    state: started
